//! Golden block fixtures from Polygon mainnet.
//!
//! ## Two sources of data:
//!
//! 1. **`generated.rs`** — Auto-generated by `scripts/fetch_golden_blocks.py` with real
//!    on-chain data (header hashes, state roots, receipt roots, etc.)
//!
//! 2. **`known_values()`** below — Hardcoded ground-truth values that we KNOW are correct
//!    independent of any RPC fetch. These serve as a fallback and sanity check.
//!
//! Run `python3 scripts/fetch_golden_blocks.py` to generate `generated.rs`.
//! Until then, use `known_values()` for testing.

// Include auto-generated fixtures when available.
// Uncomment after running fetch_golden_blocks.py:
// mod generated;
// pub use generated::*;


// ============================================================================
// KNOWN VALUES — hardcoded ground truth independent of RPC
// These are values we KNOW from the protocol spec, not from fetching blocks.
// They can be used immediately without running the fetch script.
// ============================================================================

/// Block selection catalog with expected parameter values.
/// Use these to test parameter functions WITHOUT needing real block data.
pub fn known_parameter_blocks() -> Vec<KnownParameterBlock> {
    vec![
        // === PRE-DELHI ERA ===
        KnownParameterBlock {
            block: 1_000_000,
            era: "pre-Delhi",
            sprint_size: 64,
            span_size: 6400,
            gas_limit_era: 30_000_000,
            base_fee_denom: 8,
            is_post_madhugiri: false,
        },
        KnownParameterBlock {
            block: 30_000_000,
            era: "pre-Delhi",
            sprint_size: 64,
            span_size: 6400,
            gas_limit_era: 30_000_000,
            base_fee_denom: 8,
            is_post_madhugiri: false,
        },
        KnownParameterBlock {
            block: 38_189_055,
            era: "pre-Delhi (last block)",
            sprint_size: 64,
            span_size: 6400,
            gas_limit_era: 30_000_000,
            base_fee_denom: 8,
            is_post_madhugiri: false,
        },

        // === DELHI BOUNDARY ===
        KnownParameterBlock {
            block: 38_189_056,
            era: "Delhi (activation)",
            sprint_size: 16,
            span_size: 6400,
            gas_limit_era: 30_000_000,
            base_fee_denom: 16,
            is_post_madhugiri: false,
        },
        KnownParameterBlock {
            block: 38_189_072,
            era: "post-Delhi (first sprint-16 boundary)",
            sprint_size: 16,
            span_size: 6400,
            gas_limit_era: 30_000_000,
            base_fee_denom: 16,
            is_post_madhugiri: false,
        },

        // === AGRA MID-SPRINT ===
        KnownParameterBlock {
            block: 50_522_999,
            era: "pre-Agra (last block)",
            sprint_size: 16,
            span_size: 6400,
            gas_limit_era: 30_000_000,
            base_fee_denom: 16,
            is_post_madhugiri: false,
        },
        KnownParameterBlock {
            block: 50_523_000,
            era: "Agra (mid-sprint! 50523000 % 16 = 8)",
            sprint_size: 16,
            span_size: 6400,
            gas_limit_era: 30_000_000,
            base_fee_denom: 16,
            is_post_madhugiri: false,
        },

        // === BHILAI GAS LIMIT TRANSITION ===
        KnownParameterBlock {
            block: 75_999_999,
            era: "pre-Bhilai (last 30M gas)",
            sprint_size: 16,
            span_size: 6400,
            gas_limit_era: 30_000_000,
            base_fee_denom: 16,
            is_post_madhugiri: false,
        },
        KnownParameterBlock {
            block: 76_000_000,
            era: "Bhilai (gas 30M→45M)",
            sprint_size: 16,
            span_size: 6400,
            gas_limit_era: 45_000_000,
            base_fee_denom: 64,
            is_post_madhugiri: false,
        },

        // === RIO SPAN TRANSITION ===
        KnownParameterBlock {
            block: 77_414_655,
            era: "pre-Rio (last span=6400)",
            sprint_size: 16,
            span_size: 6400,
            gas_limit_era: 45_000_000,
            base_fee_denom: 64,
            is_post_madhugiri: false,
        },
        KnownParameterBlock {
            block: 77_414_656,
            era: "Rio (span 6400→1600)",
            sprint_size: 16,
            span_size: 1600,
            gas_limit_era: 45_000_000,
            base_fee_denom: 64,
            is_post_madhugiri: false,
        },

        // === MADHUGIRI RECEIPT TRANSITION ===
        KnownParameterBlock {
            block: 80_084_799,
            era: "pre-Madhugiri (last separate receipts)",
            sprint_size: 16,
            span_size: 1600,
            gas_limit_era: 45_000_000,
            base_fee_denom: 64,
            is_post_madhugiri: false,
        },
        KnownParameterBlock {
            block: 80_084_800,
            era: "Madhugiri (receipts unified)",
            sprint_size: 16,
            span_size: 1600,
            gas_limit_era: 45_000_000,
            base_fee_denom: 64,
            is_post_madhugiri: true,
        },

        // === LISOVO MID-SPRINT ===
        KnownParameterBlock {
            block: 83_756_499,
            era: "pre-Lisovo (last block)",
            sprint_size: 16,
            span_size: 1600,
            gas_limit_era: 45_000_000,
            base_fee_denom: 64,
            is_post_madhugiri: true,
        },
        KnownParameterBlock {
            block: 83_756_500,
            era: "Lisovo (mid-sprint! 83756500 % 16 = 4)",
            sprint_size: 16,
            span_size: 1600,
            gas_limit_era: 45_000_000,
            base_fee_denom: 64,
            is_post_madhugiri: true,
        },
    ]
}

/// Known boundary conditions — blocks that are on specific boundaries.
pub fn known_boundary_blocks() -> Vec<KnownBoundaryBlock> {
    vec![
        // Sprint boundaries (block % sprint_size == 0)
        KnownBoundaryBlock { block: 38_188_992, is_sprint_start: true, sprint_size: 64, is_span_start: false, span_size: 6400 },
        KnownBoundaryBlock { block: 38_189_056, is_sprint_start: true, sprint_size: 16, is_span_start: false, span_size: 6400 },  // Delhi itself
        KnownBoundaryBlock { block: 38_189_072, is_sprint_start: true, sprint_size: 16, is_span_start: false, span_size: 6400 },
        KnownBoundaryBlock { block: 50_523_000, is_sprint_start: false, sprint_size: 16, is_span_start: false, span_size: 6400 }, // Agra: 50523000 % 16 = 8, NOT sprint start!
        KnownBoundaryBlock { block: 83_756_500, is_sprint_start: false, sprint_size: 16, is_span_start: false, span_size: 1600 }, // Lisovo: 83756500 % 16 = 4, NOT sprint start!

        // Span boundaries (block % span_size == 0)
        KnownBoundaryBlock { block: 51_200,     is_sprint_start: true,  sprint_size: 16, is_span_start: true,  span_size: 6400 },  // span 8
        KnownBoundaryBlock { block: 6_400,      is_sprint_start: true,  sprint_size: 64, is_span_start: true,  span_size: 6400 },  // span 1 (pre-Delhi)
        KnownBoundaryBlock { block: 77_416_000, is_sprint_start: true,  sprint_size: 16, is_span_start: true,  span_size: 1600 },  // first post-Rio span boundary (77416000 % 1600 == 0)

        // Block 0 special case
        KnownBoundaryBlock { block: 0, is_sprint_start: false, sprint_size: 64, is_span_start: false, span_size: 6400 },

        // Mid-sprint hardfork blocks (NOT sprint boundaries!)
        KnownBoundaryBlock { block: 50_523_000, is_sprint_start: false, sprint_size: 16, is_span_start: false, span_size: 6400 }, // Agra
        KnownBoundaryBlock { block: 83_756_500, is_sprint_start: false, sprint_size: 16, is_span_start: false, span_size: 1600 }, // Lisovo
    ]
}

/// Known mid-sprint hardfork details.
pub fn mid_sprint_hardforks() -> Vec<MidSprintHardfork> {
    vec![
        MidSprintHardfork {
            name: "Agra",
            block: 50_523_000,
            block_mod_16: 8,
            sprint_containing_start: 50_522_992,
            sprint_containing_end: 50_523_007,
            next_sprint_start: 50_523_008,
        },
        MidSprintHardfork {
            name: "Lisovo",
            block: 83_756_500,
            block_mod_16: 4,
            sprint_containing_start: 83_756_496,
            sprint_containing_end: 83_756_511,
            next_sprint_start: 83_756_512,
        },
    ]
}

// ============================================================================
// Types
// ============================================================================

/// A block with known parameter values (from protocol spec, not chain data).
#[derive(Debug, Clone)]
pub struct KnownParameterBlock {
    pub block: u64,
    pub era: &'static str,
    pub sprint_size: u64,
    pub span_size: u64,
    pub gas_limit_era: u64,
    pub base_fee_denom: u64,
    pub is_post_madhugiri: bool,
}

/// A block with known boundary conditions.
#[derive(Debug, Clone)]
pub struct KnownBoundaryBlock {
    pub block: u64,
    pub is_sprint_start: bool,
    pub sprint_size: u64,
    pub is_span_start: bool,
    pub span_size: u64,
}

/// A hardfork that activates mid-sprint.
#[derive(Debug, Clone)]
pub struct MidSprintHardfork {
    pub name: &'static str,
    pub block: u64,
    pub block_mod_16: u64,
    pub sprint_containing_start: u64,
    pub sprint_containing_end: u64,
    pub next_sprint_start: u64,
}
